baseurl                  = "https://www.canobbioe.com/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "The art of BEEP-BOOPing"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = ""
    homepage             = "home"
    footerText           = "=)"

# Metadata for Open Graph and Twitter
    description          = "A programming (not only) blog, with cookies." 
    images               = ["tn.png"] 
    title                = "The art of BEEP-BOOPing"

[[params.mainMenu]]
    link = "/posts"
    text = "articles"

[[params.mainMenu]]
    link = "/about"
    text = "about"

[imaging]
    quality = 75